### ISSUE TITLE
Server上存的dataset無法解壓縮

### ISSUE THREAD

**Issue by FallwinDs** [2019-dl-training-program/Lab3#1]
在server上助教提供的dataset只有image_info_test2014.zip和train2014.zip可以解壓縮
其他幾個zip檔annotations_trainval2014.zip, test2014.zip和val2014.zip都無法用archive manager打開或解壓縮
參照download.sh裡面的unzip指令也會出現以下訊息
 End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.
unzip: cannot find zipfile directory in one of ./data/test2014.zip or ./data/test2014.zip.zip, and cannot find ./data/test2014.zip.ZIP, period.

用jar xvf test2014.zip可以解出一部份，但是最後還是會有unexpected EOF的訊息出現
請問助教該dataset要如何解開? train/test/val的總張數是幾張?

**Comment by zivzone** [comment]
Training dataset的zip檔應該是13GB大小的
