### ISSUE TITLE
train dataset 的大小問題？ 是不是該請 IT 下載放到共用空間？

### ISSUE THREAD

**Issue by ziyu4huang** [2019-dl-training-program/Lab3#2]
大部份人的個人account 放 13G的壓力應該很大吧，這個些trainning data 是不是能下載到一個共用區避免浪費大家資源下載？而不是每個人都下載

這動作最好由公司IT來做

**Comment by zivzone** [comment]
有的，我們有請IT幫忙放到公共區域供大家下載，在Lab3正式開始之前應該是可以放置完
