### ISSUE TITLE
Error: unable to access ' https://github.com/pdollar/coco.git'

### ISSUE THREAD

**Issue by WenChouWu** [2019-dl-training-program/Lab3#3]
I just try to execute the commends in our RD domain but meet the download issue as title. Should we need to perform those commends for Lab3?

$ git clone https://github.com/pdollar/coco.git
$ cd coco/PythonAPI/
$ make
$ python setup.py build
$ python setup.py install
$ cd ../../
$ git clone https://github.com/2019-dl-training-program/Lab3

**Comment by zkostree** [comment]
公司防火牆會擋掉，我的作法是先在 local 筆電 clone 好 coco
再透過 FTP 放進去來安裝

**Comment by WenChouWu** [comment]
@zkostree just follow your suggestion and I had solved this issue. Many thanks for the help.

**Comment by zivzone** [comment]
公司內部IT於禮拜三有解釋相關安裝、使用流程了，所以我們把這個issue關了
