### ISSUE TITLE
return value in def forward(), DIY_LSTM.py and batch-size in PackedSequence

### ISSUE THREAD

**Issue by mtk12585** [2019-dl-training-program/Lab3#5]
Hi,
def forward()的return看起來怪怪的，和pytorch官方的LSTM return值說明好像不太一樣
`return hidden_state_list, (hidden_state_list, cell_state_list)`

另外PackedSequence裡面的batch-size有變化的話，請問有建議要怎麼餵食給LSTM cell，執行起來會比較有效率嗎？

感謝感謝QQ

**Comment by zivzone** [comment]
如果覺得這個return 值的寫法不太接受,可以改一下寫法,但在呼叫mylstm的地方也要適當修改!
建議可以用個 If-else 先確定現在的batch size 跟之前是否一樣大然後決定現在要跑多長的batch或者可以使用兩個 for 迴圈這樣
